version: '3.9'

services:
  api:
    build: ./
    container_name: node-api
    restart: on-failure
    ports:
      - 80:${PORT}
    volumes:
      - node_module:/app/node_modules
      - .:/app
    depends_on:
      - db
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${DB_DEV_PWD}

  cache:
    image: redis:alpine
    container_name: redis-cache 
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes: 
      - cache:/data

  db:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_DEV_PWD}
      MYSQL_DATABASE: ${DB_DEV_NAME}
      MYSQL_ROOT_USER: ${DB_DEV_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
  db-test:
    image: mysql
    container_name: mysql-db-test
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_TEST_PWD}
      MYSQL_DATABASE: ${DB_TEST_NAME}
      MYSQL_ROOT_USER: ${DB_TEST_USERNAME}
    volumes:
      - db_test_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_DEV_PWD}
      MYSQL_ROOT_USER: ${DB_DEV_USERNAME}
    restart: always
    
volumes:
  dbdata:
  cache:
  node_module:
  db_test_data: